# Generated by Django 4.2.3 on 2023-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bannerimage',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_image'),
        ),
    ]
