# Generated by Django 4.2.3 on 2023-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0003_remove_category_bannerimage_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
