# Generated by Django 4.2.3 on 2023-07-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='product_image'),
        ),
    ]
