# Generated by Django 4.2.3 on 2023-07-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0012_alter_product_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
