# Generated by Django 4.2.3 on 2023-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0013_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_image',
            field=models.ImageField(upload_to='Variants'),
        ),
    ]
