# Generated by Django 4.2.3 on 2023-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0016_remove_variant_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='products'),
        ),
    ]
