# Generated by Django 4.2.3 on 2023-07-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0017_alter_product_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pa.image')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pa.variant')),
            ],
        ),
        migrations.DeleteModel(
            name='product_image',
        ),
    ]
