# Generated by Django 4.2.3 on 2023-07-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_coupon'),
        ('admin_pa', '0021_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
