# Generated by Django 4.2.3 on 2023-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0022_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.FloatField()),
                ('total_orders', models.IntegerField()),
            ],
        ),
    ]
