# Generated by Django 4.2.3 on 2023-08-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0023_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
