# Generated by Django 4.2.3 on 2023-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0025_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='admin_pa.color'),
        ),
    ]
