# Generated by Django 4.2.3 on 2023-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pa', '0029_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
