# Generated by Django 4.2.3 on 2023-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='House_No',
            field=models.IntegerField(default=None),
        ),
    ]
