# Generated by Django 4.2.3 on 2023-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
