# Generated by Django 4.2.3 on 2023-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
