# Generated by Django 4.2.3 on 2023-08-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofile_referred_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
