# Generated by Django 4.2.3 on 2023-08-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_discountcoupon_delete_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountCoupon',
            new_name='Coupon',
        ),
    ]
