# Generated by Django 4.2.3 on 2023-08-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='applied_coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
    ]
